# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meowpass < Formula
  desc "The secret vault for developers. CLI-first, E2E encrypted."
  homepage "https://meowpass.dev"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meowrithm/meowpass-releases/releases/download/v0.2.1/meowpass_0.2.1_darwin_amd64.tar.gz"
      sha256 "b74881ab5ef4c0a66e975704dbb5dbafad9848fe7ba25f3e4f84d19c164e3456"

      define_method(:install) do
        bin.install "meowpass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meowrithm/meowpass-releases/releases/download/v0.2.1/meowpass_0.2.1_darwin_arm64.tar.gz"
      sha256 "52ec3161f486f90ef46595df978e87ba01d08eca8dde7383fc5fa0bed47d94f3"

      define_method(:install) do
        bin.install "meowpass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meowrithm/meowpass-releases/releases/download/v0.2.1/meowpass_0.2.1_linux_amd64.tar.gz"
      sha256 "fa62a062eed563839b452e9f96d9b6e58c4af18eedc5987ffe15f6925119a06e"
      define_method(:install) do
        bin.install "meowpass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meowrithm/meowpass-releases/releases/download/v0.2.1/meowpass_0.2.1_linux_arm64.tar.gz"
      sha256 "fdcccd9cf7fa153cc0af525bc4b655bf2f4e75499be8e0db0ec3387a168ab65b"
      define_method(:install) do
        bin.install "meowpass"
      end
    end
  end
end
