# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meowpass < Formula
  desc "CLI-first secret manager & AI credential gateway — encrypted at rest, brokered access for agents."
  homepage "https://meowpass.dev"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meowrithm/meowpass-releases/releases/download/v0.3.1/meowpass_0.3.1_darwin_amd64.tar.gz"
      sha256 "4979760183273a3069ed359978962b022990a9ebcffc96bb13d807f9b023dea7"

      define_method(:install) do
        bin.install "meowpass"
        bin.install_symlink "meowpass" => "mp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meowrithm/meowpass-releases/releases/download/v0.3.1/meowpass_0.3.1_darwin_arm64.tar.gz"
      sha256 "269c3387299eeb7c6d5567f788df551151b1e7155e07939a3db52f6745706ccb"

      define_method(:install) do
        bin.install "meowpass"
        bin.install_symlink "meowpass" => "mp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meowrithm/meowpass-releases/releases/download/v0.3.1/meowpass_0.3.1_linux_amd64.tar.gz"
      sha256 "54021f48e6285c7dc61ebd007c39a69b58348a1787968dd72ebadaa51783e6c0"
      define_method(:install) do
        bin.install "meowpass"
        bin.install_symlink "meowpass" => "mp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meowrithm/meowpass-releases/releases/download/v0.3.1/meowpass_0.3.1_linux_arm64.tar.gz"
      sha256 "740bce16efc0d472f1c23671a7fc3db411c33373ed1c755cba596104441851d6"
      define_method(:install) do
        bin.install "meowpass"
        bin.install_symlink "meowpass" => "mp"
      end
    end
  end
end
